export const NPS_DESIGNATIONS = [
  'National Park',
  'National Monument',
  'National Historic Site',
  'National Recreation Area',
  'National Seashore',
  'National Parkway',
  'National Battlefield',
  'National Memorial',
  'National Lakeshore',
  'National River',
  'National Reserve',
  'National Trail',
  'National Historical Park',
  'National Scenic Trail',
  'National Heritage Area',
  'National Preserve',
  'National Scenic River',
  'National Wild and Scenic River',
  'National Scenic Area',
] as const;

export const US_STATES: Record<string, string> = {
  AL: 'Alabama', AK: 'Alaska', AZ: 'Arizona', AR: 'Arkansas',
  CA: 'California', CO: 'Colorado', CT: 'Connecticut', DE: 'Delaware',
  FL: 'Florida', GA: 'Georgia', HI: 'Hawaii', ID: 'Idaho',
  IL: 'Illinois', IN: 'Indiana', IA: 'Iowa', KS: 'Kansas',
  KY: 'Kentucky', LA: 'Louisiana', ME: 'Maine', MD: 'Maryland',
  MA: 'Massachusetts', MI: 'Michigan', MN: 'Minnesota', MS: 'Mississippi',
  MO: 'Missouri', MT: 'Montana', NE: 'Nebraska', NV: 'Nevada',
  NH: 'New Hampshire', NJ: 'New Jersey', NM: 'New Mexico', NY: 'New York',
  NC: 'North Carolina', ND: 'North Dakota', OH: 'Ohio', OK: 'Oklahoma',
  OR: 'Oregon', PA: 'Pennsylvania', RI: 'Rhode Island', SC: 'South Carolina',
  SD: 'South Dakota', TN: 'Tennessee', TX: 'Texas', UT: 'Utah',
  VT: 'Vermont', VA: 'Virginia', WA: 'Washington', WV: 'West Virginia',
  WI: 'Wisconsin', WY: 'Wyoming', DC: 'D.C.', PR: 'Puerto Rico',
  VI: 'U.S. Virgin Islands', AS: 'American Samoa', GU: 'Guam', MP: 'Northern Mariana Islands',
};
